---
- name: Create openshift_tools_operator_groups
  ansible.builtin.import_tasks: create_openshift_tools_operator_groups.yml
  when: state == "present"

- name: Deleting openshift_tools_operator_groups
  ansible.builtin.import_tasks: delete_openshift_tools_operator_groups.yml
  when: state == "absent"
