---
- name: Create ComplianceProfile in OpenShift
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: compliance.openshift.io/v1alpha1
      kind: ComplianceProfile
      metadata:
        name: "{{ ocp_compliance_profiles_profile }}"
        namespace: "{{ ocp_compliance_profiles_operator_namespace }}"
      spec:
        title: "{{ ocp_compliance_profiles_profile_title }}"
        description: "{{ ocp_compliance_profiles_profile_description }}"
        # Add other profile details as needed!
  when: ocp_compliance_profiles_manage_profile == "create"

- name: Delete ComplianceProfile in OpenShift
  kubernetes.core.k8s:
    state: absent
    api_version: compliance.openshift.io/v1alpha1
    kind: ComplianceProfile
    name: "{{ ocp_compliance_profiles_profile }}"
    namespace: "{{ ocp_compliance_profiles_operator_namespace }}"
  when: ocp_compliance_profiles_manage_profile == "delete"
