- name: Install IDM replica
  redhat.rhel_idm.ipareplica:
    state: "{{ platform_idm_replica_state }}"
    hostname: "{{ platform_idm_replica_hostname }}"
    domain: "{{ platform_idm_replica_domain }}"
    realm: "{{ platform_idm_replica_realm }}"
    server: "{{ platform_idm_replica_server }}"
    principal: "{{ platform_idm_replica_principal | default(omit, true) }}"
    password: "{{ (platform_idm_replica_state == 'present') | ternary(platform_idm_replica_admin_password, omit) }}"
    dm_password: "{{ (platform_idm_replica_state == 'present') | ternary(platform_idm_replica_dm_password, omit) }}"
    setup_dns: "{{ platform_idm_replica_setup_dns }}"
    setup_ca: "{{ platform_idm_replica_setup_ca }}"
    no_host_dns: "{{ platform_idm_replica_no_host_dns }}"
    no_ntp: "{{ platform_idm_replica_no_ntp }}"
    ip_addresses: "{{ platform_idm_replica_ip_addresses | default(omit, true) }}"
    auto_forwarders: "{{ platform_idm_replica_auto_forwarders | default(omit) }}"
    forwarders: "{{ platform_idm_replica_forwarders | default(omit, true) }}"
  no_log: true
