---
platforms:
  - name: na

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_SCENARIO_DIRECTORY}/../../../roles:${ANSIBLE_ROLES_PATH}"
  playbooks:
    converge: ../utils/playbooks/utilities_mount_converge_unmount_filesystem.yml
    destroy: ../utils/playbooks/utilities_mount_destroy_unmount_filesystem.yml
    verify: ../utils/playbooks/utilities_mount_verify_unmount_filesystem.yml
    prepare: ../utils/playbooks/utilities_mount_prepare_unmount_filesystem.yml
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}

scenario:
  test_sequence:
    - prepare
    - converge
    - idempotence
    - verify
  destroy_sequence:
    - destroy
