---
platforms:
  - name: na

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_SCENARIO_DIRECTORY}/../../../roles:${ANSIBLE_ROLES_PATH}"
    K8S_AUTH_API_KEY: "${K8S_AUTH_API_KEY}"
    K8S_AUTH_HOST: "${K8S_AUTH_HOST}"
    K8S_AUTH_VERIFY_SSL: "${K8S_AUTH_VERIFY_SSL}"
  playbooks:
    prepare: ../utils/playbooks/grafana_install_prepare.yml
    converge: ../utils/playbooks/grafana_install_converge.yml
    verify: ../utils/playbooks/grafana_install_verify.yml
    destroy: ../utils/playbooks/grafana_install_destroy.yml
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}

scenario:
  test_sequence:
    - prepare
    - converge
    - idempotence
    - verify
  destroy_sequence:
    - destroy
