# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for install_gitlab

state: present
name_space: ""
install_gitlab_validate_certs: false
install_gitlab_hostname: ""
install_gitlab_storage_size: ""
install_gitlab_storage_class: ""
install_gitlab_tls_crt: ""
install_gitlab_tls_key: ""
install_gitlab_admin_user: admin
install_gitlab_admin_password: ""
install_gitlab_root_password: ""
install_gitlab_chart_version: "9.4.0"
