---
- name: Secret Replicator
  hosts: localhost
  gather_facts: false

  vars:
    # Replication toggles
    cluster_replication: true
    namespace_replication: true
    vault_push: false

    # Source secret
    source_secret_name: "source-secret-name"
    source_namespace: "source-namespace"

    # Target namespaces
    target_namespaces:
      - "dev-app"
      - "staging-app"
      - "qa-app"

    # Target clusters
    target_clusters:
      - { context: 'cluster-east', ns: 'prod' }
      - { context: 'cluster-west', ns: 'prod' }
      - { context: 'cluster-dev',  ns: 'sandbox' }


    # Hashicorp Vault
    vault_url: ""
    vault_token: ""
    vault_kv_mount: "secret"
    vault_kv_path: "{{ source_namespace }}/{{ source_secret_name }}"
    vault_namespace: ""
    vault_validate_certs: true
    vault_secret_values_base64: false
    vault_store_k8s_secret_type: true
    vault_k8s_secret_type_key: "k8s_secret_type"
    
  environment:
    K8S_AUTH_VERIFY_SSL: "no"
  #   K8S_AUTH_HOST: "{{ k8s[env].host }}"
  #   K8S_AUTH_API_KEY: "{{ k8s[env].token }}"
  #   K8S_AUTH_VERIFY_SSL: "{{ (k8s[env].verify_ssl | bool) | ternary('yes','no') }}"
  # pre_tasks:
  #   - name: Flatten all k8s[env] vars
  #     ansible.builtin.set_fact:
  #       "{{ item.key }}": "{{ item.value }}"
  #     loop: "{{ k8s[env] | dict2items }}"

  roles:
    - role: infra.ado.openshift_tools_secret_replicator