---
galaxy_info:
  author: Automation Development Office
  description: infra.ado.satellite_oidc Role
  company: Automation Development Office
  license: GPL-3.0-or-later
  min_ansible_version: "2.16.0"
  galaxy_tags:
    - satellite
    - keycloak
    - oidc
    - rhbk

dependencies: []
