- name: Ensure LDAP federation provider exists
  community.general.keycloak_user_federation:
    keycloak_url: "https://{{ rhbk_host }}/"
    keycloak_user: "{{ rhbk_admin_user }}"
    keycloak_password: "{{ rhbk_admin_password }}"
    realm: "{{ rhbk_realm }}"
    provider_id: ldap
    name: "{{ rhbk_federation_name }}"
    config: "{{ ldap_config }}"
    state: present
    validate_certs: "{{ rhbk_verify_ssl }}"
  register: rhbk_setup_federation_ldap_provider
