---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: rhel7-vm-molecule-test
    hostname: rhel7-vm-molecule-test.server.lab
  - name: rhel8-vm-molecule-test
    hostname: rhel8-vm-molecule-test.server.lab
  - name: rhel9-vm-molecule-test
    hostname: rhel9-vm-molecule-test.server.lab
  - name: rhel10-vm-molecule-test
    hostname: rhel10-vm-molecule-test.server.lab

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          rhel7-vm-molecule-test:
            ansible_host: rhel7-vm-molecule-test.server.lab
            ansible_user: root
            ansible_connection: ssh
            ansible_password: "{{ molecule_root_password }}"
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=3 -o ServerAliveInterval=15 -o ServerAliveCountMax=2"
            ansible_python_interpreter: /usr/bin/python

          rhel8-vm-molecule-test:
            ansible_host: rhel8-vm-molecule-test.server.lab
            ansible_user: root
            ansible_connection: ssh
            ansible_password: "{{ molecule_root_password }}"
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=3 -o ServerAliveInterval=15 -o ServerAliveCountMax=2"
            ansible_python_interpreter: /usr/bin/python3

          rhel9-vm-molecule-test:
            ansible_host: rhel9-vm-molecule-test.server.lab
            ansible_user: root
            ansible_connection: ssh
            ansible_password: "{{ molecule_root_password }}"
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=3 -o ServerAliveInterval=15 -o ServerAliveCountMax=2"
            ansible_python_interpreter: /usr/bin/python3

          rhel10-vm-molecule-test:
            ansible_host: rhel10-vm-molecule-test.server.lab
            ansible_user: root
            ansible_connection: ssh
            ansible_password: "{{ molecule_root_password }}"
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=3 -o ServerAliveInterval=15 -o ServerAliveCountMax=2"
            ansible_python_interpreter: /usr/bin/python3

  playbooks:
    converge: converge.yml      
  env:
    # Use a safe callback (your earlier error came from a broken yaml callback plugin)
    ANSIBLE_STDOUT_CALLBACK: default
    # Let Ansible find THIS role (we are inside roles/namespace/)
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
    K8S_AUTH_API_KEY: "${K8S_AUTH_API_KEY}"
    K8S_AUTH_HOST: "${K8S_AUTH_HOST}"
    K8S_AUTH_VERIFY_SSL: "${K8S_AUTH_VERIFY_SSL}"
    ANSIBLE_VAULT_PASSWORD_FILE: ".vault_pass"

scenario:
  name: default
  # Keep resources by default (skip destroy). Uncomment 'destroy' anytime you want cleanup.
  test_sequence:
    - dependency
    - create
    - converge
    - idempotence
    - verify

verifier:
  name: ansible
