---
galaxy_info:
  author: Automation Development Office
  description: Create a qcow2 virtual machine image from an existing base image.
  company: Automation Development Office
  
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"

dependencies: []
