---
platforms:
  - name: na

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../../roles:${ANSIBLE_ROLES_PATH}"
  playbooks:
    prepare: ${MOLECULE_PROJECT_DIRECTORY}/utils/playbooks/utilities_rhel_ext_system_roles_prepare.yml
    converge: ${MOLECULE_PROJECT_DIRECTORY}/utils/playbooks/utilities_rhel_ext_system_roles_converge.yml
    verify: ${MOLECULE_PROJECT_DIRECTORY}/utils/playbooks/utilities_rhel_ext_system_roles_verify.yml
    destroy: ${MOLECULE_PROJECT_DIRECTORY}/utils/playbooks/utilities_rhel_ext_system_roles_destroy.yml
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}

scenario:
  test_sequence:
    - prepare
    - converge
    - idempotence
    - verify
  destroy_sequence:
    - destroy
