# SPDX-License-Identifier: GPL-3.0-or-later-0
# ---
# defaults file for rhbk_manage_idp
rhbk_host: >-
  {{
    (
      rhbk_hostname
      | default(ocp_rhbk_hostname, true)
      | default(hostname, true)
      | default('', true)
    )
    | regex_replace('^https?://', '')
    | regex_replace('/.*$', '')
  }}
