# SPDX-License-Identifier: GPL-3.0-or-later-0
---
# defaults file for aap_build_ee

aap_build_ee_output_image: custom-ee:latest
aap_build_ee_build_context: /tmp/aap_build_ee
aap_build_ee_builder_executable: ansible-builder
aap_build_ee_package_manager_path: ""
aap_build_ee_ansible_core: ""
aap_build_ee_ansible_runner: ""
aap_build_ee_collections: {}
aap_build_ee_collection_files: []
