---
- name: content_views | Ensure content views for capsule is created
  ansible.builtin.include_role:
    name: redhat.satellite.content_views

- name: content_views | Publish and promote Content View
  redhat.satellite.content_view_version:
    username: "{{ platform_satellite_install_admin_username }}"
    password: "{{ platform_satellite_install_admin_password }}"
    server_url: "{{ platform_satellite_install_server_url }}"
    organization: "{{ platform_satellite_install_organization }}"
    content_view: "{{ item['name'] }}"
    lifecycle_environments: "{{ item['lifecycle_environments'] }}"
    description: "Initial version"
    version: "1.0"
    validate_certs: "{{ platform_satellite_install_validate_certs }}"
  loop: "{{ platform_satellite_install_content_views }}"
...
