---
# tasks file for infra.ado.platform_satellite_install

- name: Preliminary Check
  ansible.builtin.include_tasks: preliminary_check.yml

- name: Block tasks to run when pre_check is set to false
  when: not platform_satellite_install_pre_check
  block:
    - name: RHSM Subscribe
      ansible.builtin.include_tasks: rhsm_subscribe.yml

    - name: Patch
      ansible.builtin.include_tasks: patch.yml

    - name: Storage Config
      ansible.builtin.include_tasks: storage_config.yml

    - name: Install Packages
      ansible.builtin.include_tasks: install_packages.yml

    - name: Configure Firewall
      ansible.builtin.include_tasks: configure_firewall.yml

    - name: Prep Custom Certificates
      ansible.builtin.include_tasks: prep-custom-certs.yml

    - name: DNS Config
      ansible.builtin.include_tasks: dns_config.yml

    - name: Satellite Install
      ansible.builtin.include_tasks: install_satellite.yml

    - name: Settings Config
      ansible.builtin.include_tasks: settings.yml

    - name: Manifest Config
      ansible.builtin.include_tasks: manifest.yml

    - name: Enable Repos
      ansible.builtin.include_tasks: enable_repos.yml

    - name: Third Party Products
      ansible.builtin.include_tasks: third_party_products.yml

    - name: Repo Sync
      ansible.builtin.include_tasks: repo_sync.yml

    - name: Lifecycle Envs
      ansible.builtin.include_tasks: lifecycle_envs.yml
