---
- name: manifest | Copy the manifest to Satellite
  ansible.builtin.copy:
    src: "{{ platform_satellite_install_manifest_src }}"
    dest: "{{ platform_satellite_install_manifest_path }}"
    owner: root
    group: root
    mode: "0644"

- name: manifest | Remove the manifest
  redhat.satellite.subscription_manifest:
    username: "{{ platform_satellite_install_admin_username }}"
    password: "{{ platform_satellite_install_admin_password }}"
    server_url: "{{ platform_satellite_install_server_url }}"
    organization: "{{ platform_satellite_install_organization }}"
    state: absent
    validate_certs: "{{ platform_satellite_install_validate_certs }}"
  failed_when: false

- name: manifest | Upload the manifest for Satellite
  redhat.satellite.subscription_manifest:
    username: "{{ platform_satellite_install_admin_username }}"
    password: "{{ platform_satellite_install_admin_password }}"
    server_url: "{{ platform_satellite_install_server_url }}"
    organization: "{{ platform_satellite_install_organization }}"
    state: present
    manifest_path: "{{ platform_satellite_install_manifest_path }}"
    validate_certs: "{{ platform_satellite_install_validate_certs }}"
  failed_when: false

- name: manifest | Refresh the manifest
  redhat.satellite.subscription_manifest:
    username: "{{ platform_satellite_install_admin_username }}"
    password: "{{ platform_satellite_install_admin_password }}"
    server_url: "{{ platform_satellite_install_server_url }}"
    organization: "{{ platform_satellite_install_organization }}"
    state: refreshed
    validate_certs: "{{ platform_satellite_install_validate_certs }}"
  failed_when: false
...
