---
- name: prep-custom-certs | Create Satellite certificate directory
  ansible.builtin.file:
    path: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}"
    state: directory
    mode: "0750"

- name: prep-custom-certs | Generate server private key
  community.crypto.openssl_privatekey:
    path: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_key.pem"
    size: 4096
    mode: "0600"

- name: prep-custom-certs | Check for existing CSR
  ansible.builtin.stat:
    path: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_csr.pem"
  register: platform_satellite_install_existing_csr

- name: prep-custom-certs | Check if openssl.cnf.j2 exists
  ansible.builtin.stat:
    path: "{{ role_path }}/templates/openssl.cnf.j2"
  register: platform_satellite_install_template_check
  delegate_to: localhost

- name: Assert template exists
  ansible.builtin.assert:
    that:
      - platform_satellite_install_template_check.stat.exists
    fail_msg: "Template openssl.cnf.j2 is missing. Please add it with your satellite servers custom configurations in {{ role_path }}/templates/ !"

- name: prep-custom-certs | Generate CNF file
  ansible.builtin.template:
    src: openssl.cnf.j2
    dest: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_openssl.cnf"
    mode: "0640"

- name: prep-custom-certs | Generate CSR file
  ansible.builtin.command: >
    openssl req -new
    -key /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_key.pem
    -out /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_csr.pem
    -config /tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_openssl.cnf
  args:
    creates: "/tmp/backup/satellite-certificates/{{ inventory_hostname }}/{{ inventory_hostname }}_cert_csr.pem"
