---
platform_satellite_config_satellite_redhat_repos:
  - name: "Red Hat Satellite Capsule {{ platform_satellite_config_satellite_deployment_version }} for RHEL 9 x86_64 (RPMs)"
    label: "satellite-capsule-{{ platform_satellite_config_satellite_deployment_version }}-for-rhel-9-x86_64-rpms"
    all: "true"
  - name: "Red Hat Satellite Maintenance {{ platform_satellite_config_satellite_deployment_version }} for RHEL 9 x86_64 (RPMs)"
    label: "satellite-maintenance-{{ platform_satellite_config_satellite_deployment_version }}-for-rhel-9-x86_64-rpms"
    all: "true"
  - name: "Red Hat Satellite {{ platform_satellite_config_satellite_deployment_version }} for RHEL 9 x86_64 (RPMs)"
    label: "satellite-{{ platform_satellite_config_satellite_deployment_version }}-for-rhel-9-x86_64-rpms"
    all: "true"
  - name: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
    label: "satellite-client-6-for-rhel-9-x86_64-rpms"
    all: "true"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
    label: rhel-9-for-x86_64-baseos-rpms
    repos:
      - releasever: "9"
    all: "false"
  - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)"
    label: rhel-9-for-x86_64-appstream-rpms
    repos:
      - releasever: "9"
    all: "false"
platform_satellite_config_satellite_proxy_server: ""
platform_satellite_config_satellite_proxy_port: ""
platform_satellite_config_satellite_proxy_scheme: ""
platform_satellite_config_settings:
  - name: "default_download_policy"
    value: "immediate"
  - name: "default_redhat_download_policy"
    value: "immediate"
  - name: "default_proxy_download_policy"
    value: "immediate"
  - name: "errata_status_installable"
    value: "true"
  - name: "unregister_delete_host"
    value: "true"
  - name: "template_sync_associate"
    value: "never"
  - name: "template_sync_branch"
    value: "master"
  - name: "template_sync_force"
    value: "true"
  - name: "template_sync_lock"
    value: "true"
  - name: "db_pending_seed"
    value: "false"
  - name: "entries_per_page"
    value: "100"
  - name: "unregister_delete_host"
    value: "true"
  - name: "ignored_interface_identifiers"
    value: [ "lo", "en*v*", "usb*", "vnet*", "macvtap*", "_vdsmdummy_", "veth*", "docker*", "tap*", "qbr*", "qvb*", "qvo*", "qr-*", "qg-*", "vlinuxbr*", "vovsbr*", "bond*" ]
  - name: "host_tasks_workers_pool_size"
    value: "100"
platform_satellite_config_server_url: "https://{{ ansible_fqdn }}"
platform_satellite_config_gpg_key_files:
  - files/RPM-GPG-KEY-EPEL-9
