---
galaxy_info:
  author: Corey Sebastian Dixon
  description: infra.ado.satellite_config Role
  company: Automation Development Office
  license: GPL-3.0-or-later

  min_ansible_version: "2.14"

  galaxy_tags: []

dependencies: []
