---
platforms:
  - name: na

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_SCENARIO_DIRECTORY}/../../../roles:${ANSIBLE_ROLES_PATH}"
  playbooks:
    converge: ../utils/playbooks/manage_mounts_converge_remove_from_fstab.yml
    destroy: ../utils/playbooks/manage_mounts_destroy_remove_from_fstab.yml
    verify: ../utils/playbooks/manage_mounts_verify_remove_from_fstab.yml
    prepare: ../utils/playbooks/manage_mounts_prepare_remove_from_fstab.yml
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}

scenario:
  test_sequence:
    - prepare
    - converge
    - idempotence
    - verify
  destroy_sequence:
    - destroy
