---
- name: Verify - elastic scenario
  hosts: localhost
  gather_facts: false
  become: false

  vars:
    readme_path: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../../../roles/elastic/README.md"

  tasks:
    - name: Check if role README.md exists
      ansible.builtin.stat:
        path: "{{ readme_path }}"
      register: elastic_verify_readme_file

    - name: Assert role README.md exists
      ansible.builtin.assert:
        that:
          - elastic_verify_readme_file.stat.exists
        fail_msg: "README.md is missing for elastic."
