---
- name: Destroy gitlab_install resources
  hosts: localhost
  gather_facts: false
  vars:
    name_space: gitlab
    gitlab_install_validate_certs: false
    state: absent
  roles:
    - infra.ado.gitlab_install
