---
- name: Converge install_gitlab role
  hosts: localhost
  gather_facts: false
  vars:
    name_space: gitlab
    install_gitlab_hostname: "gitlab.apps.example.com"
    install_gitlab_storage_size: "20Gi"
    install_gitlab_storage_class: "gp2-csi"
    install_gitlab_tls_crt: "dummy-cert"
    install_gitlab_tls_key: "dummy-key"
    install_gitlab_admin_user: admin
    install_gitlab_admin_password: "changeme"
    install_gitlab_root_password: "changeme"
    install_gitlab_validate_certs: false
    state: present
  roles:
    - infra.ado.install_gitlab
