---
- name: Converge - manage_mounts mount auto-detect scenario
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    manage_mounts_test_root: /tmp/manage_mounts_molecule_mount_auto_detect
    manage_mounts_image_path: "{{ manage_mounts_test_root }}/device.img"
    manage_mounts_mount_path: "{{ manage_mounts_test_root }}/mnt"

  tasks:
    - name: Include manage_mounts role for auto-detect mount # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.ado.manage_mounts
      vars:
        mount_action: mounted
        mount_path: "{{ manage_mounts_mount_path }}"
        target_device: "{{ manage_mounts_image_path }}"
        mount_fstype_detection: true
