---
- name: Verify - platform_satellite_install scenario
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: verify | Confirm platform_satellite_install pre_check finished
      ansible.builtin.debug:
        msg: "platform_satellite_install verify step"
