---
- name: Destroy - platform_satellite_install scenario
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: destroy | No cleanup required for platform_satellite_install pre_check
      ansible.builtin.debug:
        msg: "platform_satellite_install destroy step"
