---
- name: Converge - rhel_mount mount explicit fstype scenario
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    rhel_mount_test_root: /tmp/rhel_mount_molecule_mount_explicit_fstype
    rhel_mount_image_path: "{{ rhel_mount_test_root }}/device.img"
    rhel_mount_path: "{{ rhel_mount_test_root }}/mnt"

  tasks:
    - name: Include rhel_mount role for explicit fstype mount # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.ado.rhel_mount
      vars:
        rhel_mount_action: mounted
        rhel_mount_path: "{{ rhel_mount_path }}"
        rhel_mount_target_device: "{{ rhel_mount_image_path }}"
        rhel_mount_fstype: ext4
