---
- name: Destroy — no-op (delegated driver)
  hosts: all
  gather_facts: false
  become: false
  remote_user: root

  roles:
    - role: infra.ado_platform.sat_reg
      vars:
        sat_reg_satellite_host: "https://sat.server.lab"
        sat_reg_validate_certs: false
        sat_reg_insecure: true
        sat_reg_action: deregister
