---
- name: Converge - utilities_mount remove from fstab scenario
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    utilities_mount_test_root: /tmp/utilities_mount_molecule_remove_from_fstab
    utilities_mount_mount_path: "{{ utilities_mount_test_root }}/mnt"

  tasks:
    - name: Include utilities_mount role for fstab removal # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.ado.utilities_mount
      vars:
        mount_action: absent
        mount_path: "{{ utilities_mount_mount_path }}"
