---
- name: Converge - utils_mount mount auto-detect scenario
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    utils_mount_test_root: /tmp/utils_mount_molecule_mount_auto_detect
    utils_mount_image_path: "{{ utils_mount_test_root }}/device.img"
    utils_mount_mount_path: "{{ utils_mount_test_root }}/mnt"

  tasks:
    - name: Include utils_mount role for auto-detect mount # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: infra.ado.utils_mount
      vars:
        mount_action: mounted
        mount_path: "{{ utils_mount_mount_path }}"
        target_device: "{{ utils_mount_image_path }}"
        mount_fstype_detection: true
