---
- name: lifecycle_envs | Ensure lifecycle environments are created
  redhat.satellite.lifecycle_environment:
    username: "{{ platform_satellite_config_admin_username }}"
    password: "{{ platform_satellite_config_admin_password }}"
    server_url: "{{ platform_satellite_config_server_url }}"
    organization: "{{ platform_satellite_config_organization }}"
    name: "{{ item['env_name'] }}"
    prior: "{{ item['prior'] }}"
    validate_certs: "{{ platform_satellite_config_validate_certs }}"
  loop: "{{ platform_satellite_config_lifecycle_envs }}"
...
