# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for idm_dns
idm_dns_state: present
idm_dns_ipa_host: ""
idm_dns_ipa_user: ""
idm_dns_ipa_pass: ""
idm_dns_zone: ""
idm_dns_record: ""
idm_dns_ip_address: ""
idm_dns_record_ttl: 3600
idm_dns_validate_certs: false
