---
galaxy_info:
  role_name: acs_upload_policies
  namespace: infra
  author: Automation Development Office
  description: Upload ACS policies/reports JSON from git or path
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
dependencies: []
