# SPDX-License-Identifier: GPL-3.0-or-later
---
state: present
zabbix_hostname: "{{ hostname | default('') }}"
zabbix_storage_size: 20Gi
zabbix_mariadb_image: registry.redhat.io/rhel9/mariadb-105:latest
zabbix_server_image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest
zabbix_web_image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.0-latest
zabbix_db_user: zabbix
zabbix_db_name: zabbix
zabbix_db_root_password: rootpass123!
zabbix_db_password: zabbixpass123!
zabbix_admin_user: Admin
zabbix_admin_password: redhat123
zabbix_default_admin_password: zabbix
storage: ""
zabbix_saml_enabled: false
zabbix_saml_idp_metadata_url: ""
zabbix_saml_sp_entity_id: ""
zabbix_validate_certs: false
