---
platforms:
  - name: na

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_SCENARIO_DIRECTORY}/../../../roles:${ANSIBLE_ROLES_PATH}"
  playbooks:
    prepare: ../utils/playbooks/ocp_console_banner_prepare.yml
    converge: ../utils/playbooks/ocp_console_banner_converge.yml
    verify: ../utils/playbooks/ocp_console_banner_verify.yml
    destroy: ../utils/playbooks/ocp_console_banner_destroy.yml
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}

scenario:
  test_sequence:
    - prepare
    - converge
    - idempotence
    - verify
  destroy_sequence:
    - destroy
